image: ruby:3.2

pages:
  script:
    - apt-get update -qq && apt-get install -y rsync
    - mkdir public
    - rsync -av --exclude='public' ./ public/
  artifacts:
    paths:
      - public
