image: ruby:3.2

before_script:
  - apt-get update -qq
  - apt-get install -y rsync

script:
  - mkdir -p public || echo "Directory already exists"
  - rsync -av --delete public/*.html public/*.css public/*.js ./
