image: ruby:3.2

before_script:
  - apt-get update -qq
  - apt-get install -y rsync

script:
  - [ ! -d public ] && mkdir public  
  - rsync -av --delete public/*.html public/*.css public/*.js public/
