image: ruby:3.2

before_script:
  - apt-get update -qq
  - apt-get install -y rsync

script:
  - rm -rf public 
  - mkdir public
  - rsync -av --delete source_directory/*.html source_directory/*.css source_directory/*.js public/
